CREATE DATABASE DB_GENERATION_GAME_ONLINE;
USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSES(
ID BIGINT AUTO_INCREMENT,
TIPO VARCHAR(255),
DESCRICAO VARCHAR(255),
PRIMARY KEY(ID));

CREATE TABLE TB_PERSONAGENS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
ATAQUE INT,
DEFESA INT,
CARACTERISTICA VARCHAR(255),
EQUIPAMENTO VARCHAR(255),
CLASSES_ID BIGINT,
PRIMARY KEY(ID),
FOREIGN KEY(CLASSES_ID) REFERENCES TB_CLASSES(ID));

INSERT INTO TB_CLASSES(TIPO,DESCRICAO) VALUES ("MAGO", "SOLTA FEITIÇO"), ("SOLDADO", "ATIRA"),
("XAMÃ", "INVOCA OS ELEMENTOS"), ("SACERDOTE", "CURA");

SELECT * FROM TB_CLASSES;

INSERT INTO TB_PERSONAGENS(NOME, ATAQUE, DEFESA, CARACTERISTICA, EQUIPAMENTO, CLASSES_ID) VALUES
("COBAIN", 2808, 1909, "FORTE", "ARMADURA E BAZUCA", 2), ("EDITE", 2810, 1800, "ESTRATEGISTA", "AMULETO", 3),
("GANDALF", 3502, 1589, "AMIGO", "CAJADO", 1), ("ANDUIN", 1025, 705, "ASTUTO", "ADAGA", 4);

SELECT * FROM TB_PERSONAGENS;

SELECT * FROM TB_PERSONAGENS WHERE ATAQUE >2000;
SELECT * FROM TB_PERSONAGENS WHERE DEFESA BETWEEN 1000 AND 2000;

SELECT * FROM tB_PERSONAGENS WHERE NOME LIKE "C%"; 

SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSES_ID = TB_CLASSES.ID;
SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_PERSONAGENS.CLASSES_ID = TB_CLASSES.ID WHERE TIPO = "MAGO";