CREATE DATABASE RH_GENERATION;

USE RH_GENERATION;

CREATE TABLE COLABORADORES(
ID BIGINT AUTO_INCREMENT, 
NOME VARCHAR(1000),
TELEFONE INT,
CARGO CHAR(255),
SALARIO FLOAT,
PRIMARY KEY (ID)
);

INSERT INTO COLABORADORES (NOME, TELEFONE, CARGO, SALARIO) VALUES ("MARCOS", 99999995, "DEV", 25000);

DELETE FROM COLABORADORES WHERE ID = 7;
SELECT * FROM COLABORADORES;

SET SQL_SAFE_UPDATES = 0;

SELECT * FROM COLABORADORES;

SELECT * FROM COLABORADORES WHERE SALARIO > 2000;
SELECT * FROM COLABORADORES WHERE SALARIO < 2000;

UPDATE COLABORADORES SET SALARIO = 1800 WHERE ID = 3;
SELECT * FROM COLABORADORES;




