CREATE DATABASE ECOMMERCE;

USE ECOMMERCE;

CREATE TABLE LOJA(
ID BIGINT AUTO_INCREMENT,
ROUPA CHAR(255),
MARCA CHAR(255),
PRECO FLOAT,
TAMANHO CHAR(255),
TECIDO CHAR(255),
PRIMARY KEY (ID)
);

INSERT INTO LOJA (ROUPA, MARCA, PRECO, TAMANHO, TECIDO) VALUES ("SEGUNDA PELE", "RENNER", 75, "P", "MALHA");

SELECT * FROM LOJA;

SELECT * FROM LOJA WHERE PRECO >500;
SELECT * FROM LOJA WHERE PREÇO <500;

SELECT * FROM LOJA;

SET SQL_SAFE_UPDATES = 0;

UPDATE LOJA SET PRECO = 502 WHERE ID = 3;
SELECT * FROM LOJA;


