CREATE DATABASE ESCOLA;

USE ESCOLA;

CREATE TABLE NOTASDOSALUNOS(
RA BIGINT AUTO_INCREMENT, 
NOME VARCHAR(1000),
TELEFONE INT,
SERIE CHAR(255),
PERIODO CHAR(255),
NOTA FLOAT,
PRIMARY KEY (RA)
);

INSERT INTO NOTASDOSALUNOS (NOME, TELEFONE, SERIE, PERIODO, NOTA) VALUES ("MARCOS SILVA", 999999992, "2ANOC", "NOTURNO", 7.5);

SELECT * FROM NOTASDOSALUNOS;

SELECT * FROM NOTASDOSALUNOS WHERE NOTA >7;
SELECT * FROM NOTASDOSALUNOS WHERE NOTA <7;

SELECT * FROM NOTASDOSALUNOS;

SET SQL_SAFE_UPDATES = 0;

UPDATE NOTASDOSALUNOS SET NOTA = 10 WHERE RA = 2;
SELECT * FROM NOTASDOSALUNOS;
